# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 18:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import orchestra.contrib.mailboxes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0002_auto_20160219_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='custom_filtering',
            field=models.TextField(blank=True, help_text="Arbitrary email filtering in <a href='https://tty1.net/blog/2011/sieve-tutorial_en.html'>sieve language</a>. This overrides any automatic junk email filtering", validators=[orchestra.contrib.mailboxes.validators.validate_sieve], verbose_name='filtering'),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='name',
            field=models.CharField(db_index=True, help_text='Required. 32 characters or fewer. Letters, digits and ./-/_ only.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.-]+$', 'Enter a valid mailbox name.')], verbose_name='name'),
        ),
    ]
