from django.conf import settings


DAEMONS_SSH_DEFAULT_USER = getattr(settings, 'DAEMONS_SSH_DEFAULT_USER', 'root')

DAEMONS_SSH_DEFAULT_HOST_KEYS = getattr(settings, 'DAEMONS_SSH_DEFAULT_HOST_KEYS', '')

DAEMONS_SSH_DEFAULT_PRIVATE_KEY = getattr(settings, 'DAEMONS_SSH_DEFAULT_PRIVATE_KEY', 22)

DAEMONS_SSH_DEFAULT_PORT = getattr(settings, 'DAEMONS_SSH_DEFAULT_PORT', 80)

