# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0007_auto_20170528_2011'),
        ('webapps', '0002_auto_20170528_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapp',
            name='target_server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='webapps', to='orchestration.Server', verbose_name='Target Server'),
            preserve_default=False,
        ),
    ]
