# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_auto_20170528_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
