# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import orchestra.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='address_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains.Domain', verbose_name='address domain'),
        ),
        migrations.AlterField(
            model_name='list',
            name='address_name',
            field=models.CharField(blank=True, max_length=52, validators=[orchestra.core.validators.validate_name], verbose_name='address name'),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(help_text='Default list address &lt;name&gt;@grups.pangea.org', max_length=52, unique=True, validators=[orchestra.core.validators.validate_name], verbose_name='name'),
        ),
    ]
